# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('qtdQuartos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesAno', models.TextField(default=b'', max_length=30)),
                ('dataPagamento', models.DateField()),
                ('valorPago', models.IntegerField()),
                ('valorPagar', models.IntegerField()),
                ('apartamento', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='AppCondominio.Apartamento')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesAno', models.TextField(default=b'', max_length=30)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemCondominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.TextField(default=b'', max_length=30)),
                ('valor', models.IntegerField()),
                ('despesa', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='AppCondominio.Despesa')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=b'', max_length=50)),
                ('telefone', models.CharField(default=b'', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=b'', max_length=30)),
                ('valorRateado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='tipoDespesa',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='AppCondominio.TipoDespesa'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='itens',
            field=models.ManyToManyField(default=False, to='AppCondominio.ItemCondominio'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='proprietario',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='AppCondominio.Proprietario'),
        ),
    ]
