# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('qtdQuartos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='apartamento',
            name='propri',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='AppCondominio.Proprietario'),
        ),
    ]
