# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-22 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCondominio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proprietario',
            name='nome',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='proprietario',
            name='telefone',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
