# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCondominio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('string', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='apartamento',
            name='propri',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='AppCondominio.Proprietario'),
            preserve_default=False,
        ),
    ]
