# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCondominio', '0002_auto_20180522_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesAno', models.TextField(default=b'', max_length=30)),
                ('dataPagamento', models.DateField()),
                ('valorPago', models.IntegerField()),
                ('valorPagar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesAno', models.TextField(default=b'', max_length=30)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemCondominio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.TextField(default=b'', max_length=30)),
                ('valor', models.IntegerField()),
                ('despesa', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='AppCondominio.Despesa')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=b'', max_length=30)),
                ('valorRateado', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='apartamento',
            old_name='propri',
            new_name='proprietario',
        ),
        migrations.AddField(
            model_name='despesa',
            name='tipoDespesa',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='AppCondominio.TipoDespesa'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='apartamento',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='AppCondominio.Apartamento'),
        ),
        migrations.AddField(
            model_name='condominio',
            name='itens',
            field=models.ManyToManyField(default=False, to='AppCondominio.ItemCondominio'),
        ),
    ]
