# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCondominio', '0002_auto_20180531_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='itens',
            field=models.ManyToManyField(default=False, to='AppCondominio.ItemCondominio'),
        ),
    ]
