# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCondominio', '0003_auto_20180531_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condominio',
            name='dataPagamento',
            field=models.IntegerField(),
        ),
    ]
